### ISSUE TITLE
Bullet physics paths

### ISSUE THREAD

**Issue by ghost** [David-Parker/MyneCraft#29]
The compile progress fails because Bullet physics libs paths are not correct.
Id had to change all include paths from 

`BulletCollision/BroadphaseCollision/btBroadphaseProxy.h.`

to sth like 

`bullet/BulletCollision/BroadphaseCollision/btBroadphaseProxy.h.`

I use bullet physics SDK 2.8 @ Linux (Ubuntu 15.04).
After 2 hours id gave it up.

Is there a better solution than changing thousand of `#include` lines ?

(Sorry for my english)
Thanks in advance

**Comment by David-Parker** [comment]
Hello, it looks like you installed your Bullet in a different location. You need bullet to be installed in a known include directory, try using something like cmake or the likes.

**Comment by gamecompiler** [comment]
Id solved it now. Im using the ogre-bullet source now.
Thank you very much ^^ (The directorys are different for the current bullet fork and ogre own ones)

(Sorry for my english)
